export const PHONE_COUNTRIES = [
  { code: 'CM', dialCode: '+237', name: 'Cameroun' },
  { code: 'FR', dialCode: '+33', name: 'France' },
  { code: 'BE', dialCode: '+32', name: 'Belgique' },
  { code: 'CH', dialCode: '+41', name: 'Suisse' },
  { code: 'CA', dialCode: '+1', name: 'Canada' },
  { code: 'US', dialCode: '+1', name: 'États-Unis' },
  { code: 'GB', dialCode: '+44', name: 'Royaume-Uni' },
  { code: 'DE', dialCode: '+49', name: 'Allemagne' },
  { code: 'IT', dialCode: '+39', name: 'Italie' },
  { code: 'ES', dialCode: '+34', name: 'Espagne' },
  { code: 'CI', dialCode: '+225', name: "Côte d'Ivoire" },
  { code: 'SN', dialCode: '+221', name: 'Sénégal' },
  { code: 'GA', dialCode: '+241', name: 'Gabon' },
  { code: 'CG', dialCode: '+242', name: 'Congo' },
  { code: 'CD', dialCode: '+243', name: 'RDC' },
  { code: 'BJ', dialCode: '+229', name: 'Bénin' },
  { code: 'TG', dialCode: '+228', name: 'Togo' },
  { code: 'MA', dialCode: '+212', name: 'Maroc' },
  { code: 'AE', dialCode: '+971', name: 'Émirats arabes unis' },
] as const;
