import type { Listing, Service } from './types';

export const demoArtisans = [
  {
    id: 'demo-artisan-tchinda-bois',
    name: 'Tchinda Bois',
    specialty: 'Menuiserie & sculpture bois',
    city: 'Dschang',
    whatsapp: '+237 650 123 456',
    description: 'Meubles en bois massif, portes, tabourets et sculptures décoratives avec finitions naturelles.',
    imageUrl: '/images/DSC1514-scaled.jpg',
  },
  {
    id: 'demo-artisan-mado-fashion',
    name: 'Mado Fashion',
    specialty: 'Couture sur mesure',
    city: 'Yaoundé',
    whatsapp: '+237 651 987 321',
    description: 'Robes sur mesure, tenues traditionnelles, wax, bazin et toghu avec retouches propres.',
    imageUrl: '/images/couture.jpg',
  },
  {
    id: 'demo-artisan-atelier-soleil',
    name: 'Atelier Soleil',
    specialty: 'Décoration artisanale',
    city: 'Kribi',
    whatsapp: '+237 652 444 789',
    description: 'Objets décoratifs en rotin, bambou et fibres naturelles pour maisons, bureaux et restaurants.',
    imageUrl: '/images/african-marketplace-artisan-stockcake.jpg',
  },
];

export const demoListings: Listing[] = [
  {
    id: 'demo-panier-vannerie',
    sellerId: demoArtisans[2].id,
    seller: { id: demoArtisans[2].id, name: 'Atelier Soleil', email: 'atelier-soleil@example.test', role: 'artisan', gender: 'cooperative' },
    title: 'Panier en vannerie',
    description: 'Panier artisanal tressé à la main, idéal pour la décoration ou le rangement.',
    category: 'vannerie',
    type: 'product',
    price: '6500',
    imageUrl: '/images/il_800x800.6461226973_putg.jpg',
    imageUrls: ['/images/il_800x800.6461226973_putg.jpg'],
    status: 'active',
    stock: 5,
    createdAt: '2026-09-12',
  },
  {
    id: 'demo-tabouret-bois',
    sellerId: demoArtisans[0].id,
    seller: { id: demoArtisans[0].id, name: 'Tchinda Bois', email: 'tchinda@example.test', role: 'artisan', gender: 'male' },
    title: 'Tabouret en bois massif',
    description: 'Tabouret sculpté en bois local, finition naturelle.',
    category: 'ameublement',
    type: 'product',
    price: '12000',
    imageUrl: '/images/f45c887b1aa2f66753a697b6fe5c2c2c.jpg',
    imageUrls: ['/images/f45c887b1aa2f66753a697b6fe5c2c2c.jpg'],
    status: 'active',
    stock: 3,
    createdAt: '2026-09-12',
  },
  {
    id: 'demo-masque-bamileke',
    sellerId: 'demo-artisan-nji-sculpture',
    seller: { id: 'demo-artisan-nji-sculpture', name: 'Nji Sculpture', email: 'nji@example.test', role: 'artisan', gender: 'male' },
    title: 'Masque traditionnel Bamileke',
    description: 'Masque décoratif sculpté à la main, parfait pour salon ou bureau.',
    category: 'sculpture',
    type: 'product',
    price: '18000',
    imageUrl: '/images/thkgallery-beckwith-fisher-bamileke-elephant-mask-cameroon.jpg',
    imageUrls: ['/images/thkgallery-beckwith-fisher-bamileke-elephant-mask-cameroon.jpg'],
    status: 'active',
    stock: 2,
    createdAt: '2026-09-12',
  },
  {
    id: 'demo-sac-wax',
    sellerId: demoArtisans[1].id,
    seller: { id: demoArtisans[1].id, name: 'Mado Fashion', email: 'mado@example.test', role: 'artisan', gender: 'female' },
    title: 'Sac artisanal en tissu africain',
    description: 'Sac cousu en tissu wax, doublure intérieure et fermeture zip.',
    category: 'mode',
    type: 'product',
    price: '7000',
    imageUrl: '/images/il_1588xN.6377652826_kjkt.jpg',
    imageUrls: ['/images/il_1588xN.6377652826_kjkt.jpg'],
    status: 'active',
    stock: 8,
    createdAt: '2026-09-12',
  },
  {
    id: 'demo-robe-toghu',
    sellerId: demoArtisans[1].id,
    seller: { id: demoArtisans[1].id, name: 'Mado Fashion', email: 'mado@example.test', role: 'artisan', gender: 'female' },
    title: 'Robe en tissu toghu',
    description: 'Robe traditionnelle brodée, confection sur mesure.',
    category: 'tissage',
    type: 'product',
    price: '25000',
    imageUrl: '/images/34bac4234a643e887eb57ade20e586b5.jpg',
    imageUrls: ['/images/34bac4234a643e887eb57ade20e586b5.jpg'],
    status: 'active',
    stock: 4,
    createdAt: '2026-09-12',
  },
  {
    id: 'demo-miroir-rotin',
    sellerId: demoArtisans[2].id,
    seller: { id: demoArtisans[2].id, name: 'Atelier Soleil', email: 'atelier-soleil@example.test', role: 'artisan', gender: 'cooperative' },
    title: 'Miroir décoratif en rotin',
    description: 'Miroir mural en rotin tressé, style naturel.',
    category: 'vannerie',
    type: 'product',
    price: '9500',
    imageUrl: '/images/rattan-arched-mirror-natural-decor-947.webp',
    imageUrls: ['/images/rattan-arched-mirror-natural-decor-947.webp'],
    status: 'active',
    stock: 6,
    createdAt: '2026-09-12',
  },
];

export const demoServices: Service[] = [
  {
    id: 'demo-service-menuiserie-portes',
    title: 'Menuiserie - Fabrication de portes',
    description: 'Fabrication de portes en bois massif, finitions vernies ou naturelles.',
    priceMin: 35000,
    estimatedDays: 7,
    category: 'menuiserie',
    status: 'approved',
    createdAt: '2026-09-12',
    updatedAt: '2026-09-12',
    artisan: { id: demoArtisans[0].id, name: 'Tchinda Bois', email: 'tchinda@example.test', role: 'artisan', gender: 'male' },
    averageRating: 4.8,
    reviewCount: 6,
  },
  {
    id: 'demo-service-couture-robe',
    title: 'Couture - Robe sur mesure',
    description: 'Confection de robes sur mesure en tissu wax, toghu ou bazin.',
    priceMin: 15000,
    estimatedDays: 5,
    category: 'couture',
    status: 'approved',
    createdAt: '2026-09-12',
    updatedAt: '2026-09-12',
    artisan: { id: demoArtisans[1].id, name: 'Mado Fashion', email: 'mado@example.test', role: 'artisan', gender: 'female' },
    averageRating: 4.9,
    reviewCount: 8,
  },
  {
    id: 'demo-service-plomberie-fuites',
    title: 'Plomberie - Réparation de fuites',
    description: 'Intervention rapide pour fuites, tuyaux cassés et robinets défectueux.',
    priceMin: 5000,
    estimatedDays: 1,
    category: 'plomberie',
    status: 'approved',
    createdAt: '2026-09-12',
    updatedAt: '2026-09-12',
    averageRating: 4.6,
    reviewCount: 4,
  },
  {
    id: 'demo-service-electricite-luminaires',
    title: 'Électricité - Installation de luminaires',
    description: 'Installation de lampes, plafonniers, interrupteurs et prises sécurisées.',
    priceMin: 8000,
    estimatedDays: 2,
    category: 'electricite',
    status: 'approved',
    createdAt: '2026-09-12',
    updatedAt: '2026-09-12',
    averageRating: 4.7,
    reviewCount: 5,
  },
  {
    id: 'demo-service-decoration-rotin',
    title: 'Décoration artisanale - Mur en rotin',
    description: 'Création de décorations murales en rotin tressé, style naturel.',
    priceMin: 12000,
    estimatedDays: 4,
    category: 'ameublement',
    status: 'approved',
    createdAt: '2026-09-12',
    updatedAt: '2026-09-12',
    artisan: { id: demoArtisans[2].id, name: 'Atelier Soleil', email: 'atelier-soleil@example.test', role: 'artisan', gender: 'cooperative' },
    averageRating: 4.8,
    reviewCount: 7,
  },
];
